# Generated by Django 6.0.4 on 2026-05-06 07:50

import django.core.validators
import django.db.models.deletion
import main.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('account_status', models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('deleted', 'Удалён')], default='active', max_length=30, verbose_name='Статус аккаунта')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=main.models.generate_order_number, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembled', 'Собран'), ('shipped', 'Передан в доставку'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('returned', 'Возвращён')], default='created', max_length=50, verbose_name='Статус заказа')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Итоговая сумма')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз'), ('post', 'Почта')], max_length=50, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(choices=[('card_online', 'Карта онлайн'), ('cash_on_delivery', 'Оплата при получении'), ('sbp', 'СБП')], max_length=50, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращён')], default='pending', max_length=30, verbose_name='Статус оплаты')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Трек-номер доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за единицу')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Промежуточная сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Заказ')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина возврата')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('worn', 'Ношенный'), ('damaged', 'С дефектом')], max_length=50, verbose_name='Состояние товара')),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('completed', 'Завершён')], default='requested', max_length=30, verbose_name='Статус возврата')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения обработки')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='main.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Корзина',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product_variant'), name='unique_customer_product_variant_cart')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='main_order_order_n_bd195e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='main_order_status_4d3738_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='main_order_payment_940ff1_idx'),
        ),
    ]
