"""
Django settings for Project_Nankuev_A project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vn86uvajcf8s_l9y%d&t#)8@&7^^&5153%kw$23*ap%k93poeg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'image_uploader_widget',
    'main',
    'catalog',
    "users.apps.UsersConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project_Nankuev_A.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.header_navigation',
                'catalog.context_processors.cart_counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project_Nankuev_A.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'project_nankuev_new',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = "users.CustomUser"

LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# CDEK integration settings
# Для реального API задайте CDEK_DEMO_MODE=false и укажите CDEK_CLIENT_ID / CDEK_CLIENT_SECRET.
CDEK_DEMO_MODE = env_bool("CDEK_DEMO_MODE", True)
CDEK_BASE_URL = os.getenv("CDEK_BASE_URL", "https://api.edu.cdek.ru/v2")
CDEK_CLIENT_ID = os.getenv("CDEK_CLIENT_ID", "")
CDEK_CLIENT_SECRET = os.getenv("CDEK_CLIENT_SECRET", "")
CDEK_FROM_CITY_CODE = int(os.getenv("CDEK_FROM_CITY_CODE", "44"))
CDEK_DEFAULT_TARIFF_CODE = int(os.getenv("CDEK_DEFAULT_TARIFF_CODE", "137"))
CDEK_DEFAULT_WEIGHT_GRAMS = int(os.getenv("CDEK_DEFAULT_WEIGHT_GRAMS", "300"))
CDEK_DEFAULT_PACKAGE_LENGTH_CM = int(os.getenv("CDEK_DEFAULT_PACKAGE_LENGTH_CM", "30"))
CDEK_DEFAULT_PACKAGE_WIDTH_CM = int(os.getenv("CDEK_DEFAULT_PACKAGE_WIDTH_CM", "20"))
CDEK_DEFAULT_PACKAGE_HEIGHT_CM = int(os.getenv("CDEK_DEFAULT_PACKAGE_HEIGHT_CM", "10"))
CDEK_REQUEST_TIMEOUT = int(os.getenv("CDEK_REQUEST_TIMEOUT", "20"))


# YooKassa integration settings
# Для тестовой ЮKassa задайте YOOKASSA_DEMO_MODE=false и укажите тестовые Shop ID / Secret Key из кабинета ЮKassa.
YOOKASSA_DEMO_MODE = env_bool("YOOKASSA_DEMO_MODE", True)
YOOKASSA_API_URL = os.getenv("YOOKASSA_API_URL", "https://api.yookassa.ru/v3")
YOOKASSA_SHOP_ID = os.getenv("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = os.getenv("YOOKASSA_SECRET_KEY", "")
YOOKASSA_RETURN_BASE_URL = os.getenv("YOOKASSA_RETURN_BASE_URL", "http://127.0.0.1:8000")
YOOKASSA_CURRENCY = os.getenv("YOOKASSA_CURRENCY", "RUB")
YOOKASSA_CAPTURE = env_bool("YOOKASSA_CAPTURE", True)
YOOKASSA_REQUEST_TIMEOUT = int(os.getenv("YOOKASSA_REQUEST_TIMEOUT", "20"))

# Email notifications
# Для реальной отправки задайте EMAIL_HOST_USER и EMAIL_HOST_PASSWORD
# паролем приложения от Yandex или Google. Если пароль не задан,
# письма будут выводиться в консоль разработки.
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.yandex.ru")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", True)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "amirnankuev@yandex.ru")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")
EMAIL_NOTIFICATIONS_ENABLED = env_bool("EMAIL_NOTIFICATIONS_ENABLED", True)

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")

